### PR TITLE
Deprecate repository in lieu of Go port

### PR DESCRIPTION
**Pull request by jszwedko**
This deprecates in lieu of the go port.

Differences from this version are documented here https://github.com/hamfist/go-git-duet#differences-from-ruby-git-duet , but I've copied them below:

* Running git solo or git duet with no initials outputs configuration in same format as when setting (env variables)
* Does not set user.name and user.email (instead only sets namespaced variables) so that git commit continues to work as normal
* Template format is now Go's text/template

The change I am least sure about is not `user.name` and `user.email`. To me it feels like it may be confusing if it does set `user.name` and you do something like:
- `git duet js sd`
- `git config user.name foo`
- `git duet-commit  # Author will still be whatever js is`

This way at least separates the usage of `git commit` and `git duet-commit` completely.

Another option is only use the namespaced config for the committer and mtime, but use the user.name and user.email to set the author during `git duet-commit`.

Let me know if anyone thinks any of the above should change before merging this.

### CODE REVIEW

**Comment by jszwedko** [comment]
Picking on @tomwhoiscontrary @voelzmo specifically since you both had PRs recently so I imagine you may be using this gem. Let me know if either of you have opinions!

And @meatballhat @rafecolton of course.

**Comment by tomwhoiscontrary** [comment]
In terms of features, this all seems great.

I'm not bothered by the user.name stuff - i see the vanilla and duet systems as completely separate, so it's completely correct that setting user.name in config should not affect the names recorded by duet-commit.

If you still feel uncomfortable about this, you would warn or abort if the vanilla name is not one of the duet names. Or even abort if any name at all is set in a repo when duet is in use. In my usage, that would almost certainly be an error - a repo is either on your own machine, where you always set a vanilla name, or on one of the team's machines, where you never set a vanilla name.

My only real concern with this change is with the use of Go at all. It moves this codebase to a worse language. And one in which distribution is a farce: "Installation: See releases page for binary downloads, place in your $PATH", the '90s are back woo! That said, i imagine someone (possibly even me) will concoct a Homebrew formula for it pretty quickly, at which point it is basically the same as a gem.

**Comment by jszwedko** [comment]
@tomwhoiscontrary thank you for the comments!

I think creating a homebrew recipe is a good idea.

Opinions of the language itself aside, I think distributing this in a binary format is an improvement over the current gem setup primarily due to "missing command" issues when running `rvm` or `rbenv` and working in a Ruby project that has a `.ruby-version`. Plus the execution time is much quicker as would be expected:

```
➜  git-duet git:(deprecate) ruby --version
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]
➜  git-duet git:(deprecate) perf stat -r 100 bundle exec bin/git-duet -q js jd

 Performance counter stats for 'bundle exec bin/git-duet -q js jd' (100 runs):

        530.039178      task-clock (msec)         #    0.994 CPUs utilized            ( +-  0.21% )
               145      context-switches          #    0.274 K/sec                    ( +-  1.01% )
                66      cpu-migrations            #    0.125 K/sec                    ( +-  0.85% )
            24,788      page-faults               #    0.047 M/sec                    ( +-  0.03% )
     1,333,907,869      cycles                    #    2.517 GHz                      ( +-  0.19% )
   <not supported>      stalled-cycles-frontend  
   <not supported>      stalled-cycles-backend   
     1,607,451,964      instructions              #    1.21  insns per cycle          ( +-  0.01% )
       342,960,085      branches                  #  647.047 M/sec                    ( +-  0.01% )
         8,873,628      branch-misses             #    2.59% of all branches          ( +-  0.04% )

       0.533484751 seconds time elapsed                                          ( +-  0.24% )
```
vs.
```
➜  go-git-duet git:(master) perf stat -r 100 ./bin/git-duet -q js jd

 Performance counter stats for './bin/git-duet -q js jd' (100 runs):

         11.255711      task-clock (msec)         #    0.864 CPUs utilized            ( +-  0.88% )
               117      context-switches          #    0.010 M/sec                    ( +-  0.84% )
                18      cpu-migrations            #    0.002 M/sec                    ( +-  2.19% )
             1,623      page-faults               #    0.144 M/sec                    ( +-  0.04% )
        25,751,865      cycles                    #    2.288 GHz                      ( +-  0.77% )
   <not supported>      stalled-cycles-frontend  
   <not supported>      stalled-cycles-backend   
        22,641,987      instructions              #    0.88  insns per cycle          ( +-  0.04% )
         4,839,333      branches                  #  429.945 M/sec                    ( +-  0.03% )
           145,850      branch-misses             #    3.01% of all branches          ( +-  0.21% )

       0.013026338 seconds time elapsed                                          ( +- 12.69% )
```

**Comment by tomwhoiscontrary** [comment]
:+1: to not having dependency problems. I can't say i've really found the existing git-duet's performance to be a problem, though.

I look forward to the Nim rewrite in a couple of years :stuck_out_tongue:.

**Comment by jszwedko** [comment]
Hehe, me too -- maybe Rust first.

**Comment by rafecolton** [comment]
My $0.02:

* The differences between the Go and Ruby libraries seem fine - not setting `user.name` is probably better so we don't pollute the global namespace
* I would love to see all of this moved to a `git-duet` GitHub org.  I went ahead and snagged it and made @meatballhat and @jszwedko owners
* Easy distribution is key to getting new users to actually try this.  Installing a Ruby gem is easy.  Not having to install Ruby is even easier.  I created the `git-duet/homebrew-tap` repo for distributing the Go version on OS X
* I *have* actually noticed the slow execution time of the Ruby version, though it has not stopped me from using it.  Making things faster is always nice

**Comment by voelzmo** [comment]
Thanks @jszwedko for notifying me about this. It seems that I am the only one a little uncomfortable with not having user.name being set by git duet - I guess this depends on your use-case and expectations.

Here is some explanation why I like the current behavior of the ruby gem:
* I either do ```git duet``` or ```git solo``` and have an alias for ```git duet-commit``` so I only use this for committing
* I always set user.name globally, so there is no dependency on repository level. I either pair at the moment, or I don't.
* Whenever author or signed-off-by in the commit message is not like I expect it to be, here is where I look first: In the project's and in the global .git/config. This is still git, after all, and if you introduce a different mechanism for determining the author, I'd find this confusing.

However, I can understand the idea that ```git duet-commit``` is something entirely separate from ```git commit``` and therefore behaves differently.

+1 for the homebrew formula, this would be really appreciated! ;)

**Comment by jszwedko** [comment]
@voelzmo thanks! I think it wouldn't be too bad to make that part configurable to support both workflows. I'll open an issue for now because I'm not sure of the best way to modify the way I abstracted the interaction with `git config`.

@rafecolton thanks for creating the org and skeleton git repo for homebrew! I'll move it over.

**Comment by jszwedko** [comment]
Merging this!

**Comment by meatballhat** [comment]
woop! :heart_eyes_cat:

**Pull request merged**
