### PR TITLE
Fix ERB tag in readme for email_template

### PR DESCRIPTION
**Pull request by voelzmo**

### CODE REVIEW

**Comment by jszwedko** [comment]
Looks like some rubocop failures from an update.

**Comment by jszwedko** [comment]
Thanks @voelzmo -- would you mind addressing the rubocop complaints since the complaints are small? I can update master and you can merge into this branch if you prefer though.

**Comment by voelzmo** [comment]
Sure, no problem. I added the rubocop fix to this PR. If you feel we should split this, go ahead and cherry-pick the commits individually ;)

**Comment by meatballhat** [comment]
Woop woop!  Thanks, @voelzmo :metal: :smiley_cat:

**Pull request merged**
